language: node_js

node_js:
  - "0.12"
  - "stable"
  - "4"
cache: false

before_script:
  - npm install -g coveralls
  - uname -a
  - lsb_release -a
  - curl http://tarantool.org/dist/public.key | sudo apt-key add -
  - echo "deb http://tarantool.org/dist/master/ubuntu `lsb_release -c -s` main" | sudo tee -a /etc/apt/sources.list.d/tarantool.list
  - sudo apt-get update

script:
   - rm -rf *.snap *.xlog
   - sudo apt-get -y install tarantool
   - ./libs/tests/setup_test.lua &
   - sleep 3
   - npm run lint
   - npm test
after_success:
   - npm run coverage